### ISSUE TITLE
Ranking perils by hazard level - ordering list and show on overview map

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#289]
It makes more sense to users to have hazards on the overview page and recommendations pages ordered by hazard level, so that the top of the vertical list and left hand end of the horizontal list is highest hazard level. 
The order is currently that of relative (and very generic) importance of hazard. Please use this order as the secondary ordering factor (Flood first, earthquake second... landslide eighth)

On the homepage, please maintain the order already present.

Related to this, the map on the hazard overview page that shows before any hazard has been clicked, has no coloured hazard levels -- only admin boundaries. We found that this is non-intuitive and looks odd.
Please can we show by default on the overview page, the map for the top-ranked hazard for that location?

**Comment by pgiraud** [comment]
I agree that the map on the overview page is counter intuitive.

But if the system automatically chooses the top-ranked hazard, how will the users know which hazard the map is currently showing?
If a hazard is chosen for the map, it should also be used for the entire page. If so, the overview is not required any more.

In my opinion, the overview page itself is counter intuitive. Some of the information is duplicated (hazard types and associated levels). To me, the overview page should have a completely different layout or should not exist at all.

**Comment by nchauvin-brgm** [comment]
I don't think that the existence of the overview page has to be called into question. We need a home/summary page for the report. It may seem to be redundant with the main menu but it has the advantage to provide *legibly* the names of the hazards. First-time users will not necessarily understand the meaning of the icons and will start navigating by clicking on the section headings. To me, the raised issue is more about the map, which I also find confusing. Since we provide an overview of the hazards, why not provide an overview of the location? This is what I did on the front cover of the PDF report: showing a world map with a pin on the selected location. On that specific overview page, the map would only be informative, no possibility of interaction with it. In this case, the layout would have to be slightly updated.

**Comment by nchauvin-brgm** [comment]
I don't think that the existence of the overview page has to be called into question. We need a home/summary page for the report. It may seem to be redundant with the main menu but it has the advantage to provide *legibly* the names of the hazard levels. First-time users will not necessarily understand the meaning of the colors and will refer to the section headings. To me, the raised issue is more about the map, which I also find confusing. Since we provide an overview of the hazards, why not provide an overview of the location? This is what I did on the front cover of the PDF report: showing a world map with a pin on the selected location. On the overview page, the map would only be informative, no possibility of interaction with it. In that case, the layout would have to be slightly updated.

**Comment by stufraser1** [comment]
I agree with Nicolas - 'I don't think that the existence of the overview
page has to be called into question'. I think its important to have an
overview page for the reasons he gives.

Regarding 'Since we provide an overview of the hazards, why not provide an
overview of the location? ': I think this does give an overview of the
location
I think interaction with the map on this overview page is somewhat useful,
as it allows the user to see that they can navigate to other levels in the
map (gives an indication of how they should navigate when the map does show
hazard levels), and allows them to view the overview of hazard levels for
those other admin units. So I think we lose something useful by making it a
static map with location pin only.

I still wonder about showing an empty map, but I agree with Pierre's point
that showing the top ranked hazard may also be confusing. This issue was
not raised in user testing by any testers, and so far the solutions
presented are not satisfactory. So at this stage I suggest that we leave
the map as it is, and focus on the re-ordering of hazards from this github
issue.
We can revisit this for Beta 2 if users of Beta 1 flag it as an issue and
if we are still not happy with it.


Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
Perils weren't correctly ordered on the report overview and detailed report mockups (secondary ordering factor misapplied). This is now corrected.

**Comment by stufraser1** [comment]
Thank you. We notice that on the latest mockup, the flood and storm surge hazards have been updated to 'river' and 'coastal' on the detailed page and overview page, but not on the home page.

We're happy with the addition of the scale and the addition of a hazard level label (e.g. medium) when hovering on the map. Thank you.

**Comment by nchauvin-brgm** [comment]
Yet, the front page mockup has been well updated... Could you please check once again? Maybe did you look at the previous version? The correct one is "Front-Office - Front page mockup (update 20151204)".
