### ISSUE TITLE
World map on PDF cover

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#466]
Hi @ingenieroariel @stufraser1 

In the design proposed by @nchauvin-brgm for the PDF report, there's a world map with a marker on the cover page.
I asked him to provide me with the file to be used and sent me the following file:
http://thor-project.brgm.fr/system/files/upload/documents/ux/pdf-report-map.svg

He told me that GFDRR asked for this image to be used since it matches the WB's visual identity.

My biggest problem will be to dynamical place the marker to the correct location if I want to used this SVG file.
Do you have any on the projection used? Hasn't the Antarctica continent been removed in this map?

Another option would be to use D3JS for this map + marker, but I'm not sure I can get the exact same visual aspect.
https://bl.ocks.org/mbostock/4479477
It can even look completely different though nice and still relevant. http://mbostock.github.io/d3/talk/20111018/azimuthal.html

**Comment by ingenieroariel** [comment]
I think using D3JS with a style that is close to the WB visual identity is a good idea. That d3js code could afterwards be reused and makes more sense than trying to edit this SVG.

The caveat is that we should use the GAUL polygons here too instead of a new dataset. Ideally we would be using the WB polygons but that is something that we can ask about internally and should be easy to adjust in the future if needed.

**Comment by nchauvin-brgm** [comment]
I would have liked to have that discussion earlier... The front page mockup was submitted three months ago. If we had been informed of the technical issue back then, we could have tried to find another solution by taking the necessary time. Today we find ourselves having to make a decision in haste.

I would have liked to work on another graphical proposal based on the D3JS solution but I am in lack of time at this very moment. If everybody agrees that the WB map can be replaced (which I find unfortunate since we had an opportunity to strengthen WB's visual identity), I would prefer the "Natural Earth projection" (first link) to be used, for it looks very close to the WB map's flat style. The sphere style (second link) is very nice but unsuitable in my view. It will not fit neatly into the gray area (between the two "curtains"), which I would like to be kept since it is consistent with the web application's front page.
