### ISSUE TITLE
Show a maintenance message while publishing

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#523]
It would be nice to redirect users to a not available page when he data is being published.

**Comment by arnaud-morvan** [comment]
I propose, in the publish script to create a ```.lock``` file in the application folder.
In pyramid we could register a filter to test if file is present and return a "site is in maintenance" page.

**Comment by pgiraud** [comment]
Can you elaborate what a "filter" means technically?

**Comment by arnaud-morvan** [comment]
I was thinking to `@subscriber(NewRequest)`, but it seems that a tween factory is more appropriate.
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#registering-tweens

I also note this : https://pypi.python.org/pypi/pyramid_maintenance/0.2
https://github.com/sickless/pyramid_maintenance/blob/master/pyramid_maintenance/__init__.py
But I think we should create our own tween, because we do not use pyramid ACL, and we have 2 apps (public/admin).

**Comment by pgiraud** [comment]
OK. Can you please give the tween hook a try?
