### ISSUE TITLE
Hazard Sets / Admin Div list not displaying same layer as UI

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#603]
The Hazard Sets / Admin Div list on thinkhazard.org displays for France EQ and FL, global data (GAR15 and GLOFRIS, respectively). In the UI, the map shows that Alfieri and SHARE-EU data are being used.

**Comment by pgiraud** [comment]
Due to a wrong apache configuration, there was an overlapping between admin and public databases.
What happened is that the data displayed in the grid was coming from the public database which was containing old (not up-to-date) data.
The configuration is fixed now.
The results are consistent now.
Please validate and close this issue if appropriate.

**Comment by stufraser1** [comment]
Now, http://thinkhazard.org/admin/admindiv_hazardsets/EQ shows hazard set as 'EQ-EUROPE-SHARE' for admin0=France.
At the same time, http://thinkhazard.org/report/85-france/EQ shows data source incorrectly as UNISDR (EQ-GLOBAL-GAR15)

FL shows the same (expected) dataset for in UI and Admin UI

**Comment by pgiraud** [comment]
Data in the public interface may differ from the one in admin interface until the data is publish. You should compare with the preview interface.

**Comment by stufraser1** [comment]
The preview interface matches. Noted, thanks.
