### ISSUE TITLE
Datasetss removed from Geonode - also removed from TH! ?

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#616]
The latest release of TH uses the regional-specific datafiles derived from CF-GLOBAL-GAR15. 
But CF-GLOBAL-GAR15 is still processed. 
CF-GLOBAL-GAR15 should be removed, as we prefer to use the regional files. Is this something that is accounted for in the harvesting process? I.e. if a dataset is removed from geonode, or metadata is updated to indicate that it shouldn't be used in TH, is it removed from the processing database?

**Comment by pgiraud** [comment]
I'll check that later today.

**Comment by pgiraud** [comment]
As far as I remember, hazard sets are not removed from the tool if they are removed from Geonode. Unless we force a new harvesting. The latter happens when the administrator launches the `harvest` command with the `--force` option, or if the processing parameters change.
This happened this morning on the production server. Then the CF-GLOBAL-GAR15 is not listed any more.
If you want to remove a dataset from TH! and still don't want to reprocess everything an other option is to invalidate the dataset by either:
 - change the quality ratings and set everything to 0 so that the hazard set is not taking precedence on local hazardsets,
 - change metadata values for one layer so that it doesn't match other layers for the same hazard set. This way the hazard set will marked as incomplete thus will not be processed nor taken into account for the decision tree.
