### ISSUE TITLE
Data Quality should not be read from mask layers

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#618]
Flood mask layer have data quality currently set to 0,0.
In the admin hazardsets page, data quality rating of layers with a mask show as 0,0, but in geonode the values are 5 (calculation method) and 2 (scientific).

It seems the admin page is incorrectly showing the data quality from mask layer, not RP layer.

It seems the RP layer data quality values are used in the decision tree, as Alfieri is used correctly for France (If values 0,0 were being used, data source would show as GAR15)

**Comment by pgiraud** [comment]
Good catch.
However, it looks like the "0" rating values are effectively taken into account. What you probably missed is that the FL-GLOBAL-GAR15 hazardset is never taken into account.

**Comment by stufraser1** [comment]
OK, when I look now, it shows that Alfieri is used for each admin division in France - which is correct.

Andy is working on the mask layers for the global data today.

**Comment by NicolasT-brgm** [comment]
Yes seems work now for CF.
But I am afraid the same issue is true for CY:
CY data are local (mostly tropical regions) if I understand well. Is there data for mainland France (VL as displayed) or should France be No data?.
Nicolas

De : Stuart Fraser [mailto:notifications@github.com]
Envoyé : mardi 12 avril 2016 14:46
À : GFDRR/thinkhazard
Objet : Re: [GFDRR/thinkhazard] Data Quality should not be read from mask layers (#618)


OK, when I look now, it shows that Alfieri is used for each admin division in France - which is correct.

Andy is working on the mask layers for the global data today.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/GFDRR/thinkhazard/issues/618#issuecomment-208886643>
P Pensez à l'environnement avant d'imprimer ce message
       Think Environment before printing

Le contenu de ce mél et de ses pièces jointes est destiné à l'usage exclusif du (des) destinataire(s) désigné(s) comme tel(s).
En cas de réception par erreur, le signaler à son expéditeur et ne pas en divulguer le contenu.
L'absence de virus a été vérifiée à l'émission, il convient néanmoins de s'assurer de l'absence de contamination à sa réception.

The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only.
If you have received this email in error please notify the system manager or  the sender immediately and do not disclose the contents to
anyone or make copies.
This email was scanned for viruses, vandals and malicious content.
