### ISSUE TITLE
Broken legend for private layers in show data source

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#778]
![image](https://user-images.githubusercontent.com/1036189/28468352-baf176a8-6e00-11e7-8a7d-05ff8493798c.png)

**Comment by stufraser1** [comment]
Possible to have TH read the layer view and download permissions in Geonode?

1 = permission is checked for 'anyone' 
0 = permission is unchecked for 'anyone' 

Use case and suggested text: 
VIEW = 0, DOWNLOAD = 0, then ‘The data set used to classify the hazard in this area is not publicly available to view or download due to licensing restrictions. Please use the User Feedback link above, to request more information and other publicly available data sets.', then ‘The data set used to classify the hazard in this area is not publicly available to view or download due to licensing restrictions. Please use the User Feedback link above, to request more information and other publicly available data sets.'

VIEW = 1, DOWNLOAD = 0, then Hazard set shows in TH!, link 'more details' directs to geonode layer page, where user is given details of download restriction (In TH, show hazard data map and legend)

VIEW = 1, DOWNLOAD = 1, then Hazard set shows in TH!, link 'more details' directs to geonode layer page for download (In TH, show hazard data map and legend)

**Comment by tonio** [comment]
Quickfix deployed to production.
![screenshot from 2017-08-03 11-02-29](https://user-images.githubusercontent.com/21686/28914233-44f97028-783b-11e7-9caa-80e81f74abf2.png)

**Comment by stufraser1** [comment]
Great, thank you. I am currently working out how to view this effectively on my computer (having already cleared the cache) but tested it with a colleague and all seems to work well.
