### ISSUE TITLE
Google searches

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#804]
Is Thinkhazard! searchable on google, with required SEO keywords etc?

**Comment by stufraser1** [comment]
@fjacon, @tonio please advise - what has been done already - can we make improvements on the current optimization?

**Comment by tonio** [comment]
The most important missings are **real** links (rather than map links, which google won't take into account).

 - On report page, sub-administrative division & neighbors links are clearly missing. (& more, it would help accessibility).

 - In addition, the home has very few link because all goes through the search. We should this highly ranked space to have links to some report page (Most common? Random?) to ease google get in.

I can dig more into the page structure to see what can be done, but those points are the most important ones from my point of view.

**Comment by stufraser1** [comment]
OK, let me know what I can do to help - do you want me to identify top 10(?) countries of most interest, for which we would like Thinkhazard to show high in Google page?

**Comment by stufraser1** [comment]
@tonio  can you confirm you need my inputs here?

**Comment by MamadioCMCC** [comment]
Currently TH is well ranked when performing hazard searches on google.
