### ISSUE TITLE
All data layers not visible 

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#851]
@fjacon @pvalsecc @tonio 
- An urgent issue to resolve please: All layers are set to 'not visible' at http://thinkhazard.org/admin/hazardsets. Many of these layers should be visible to any user.

Is it possible to retrieve the previous setting for each layer and restore them?

**Comment by tonio** [comment]
There's a request done to geonode to update visibility.
@arnaud-morvan `layer` looks incorrectly set for those request. Didn't you had the same problem with harvesting recently?

**Comment by arnaud-morvan** [comment]
Hi.
I just made a geonode 2.8 harvest on thinkhazard production server.
I've take a look at indonesia I see 3 cases:

EQ : http://thinkhazard.org/admin/preview/en/report/73768-indonesia-kalimantan-timur-kutai-timur/EQ
in "show data source" we can see the layer and "More details" is publicly available

FL : http://thinkhazard.org/admin/preview/en/report/73768-indonesia-kalimantan-timur-kutai-timur/FL
in Show data source we can see the legend and the data request return fully transparent image, we are invited to login to see the More details.

CF : http://thinkhazard.org/admin/preview/en/report/73768-indonesia-kalimantan-timur-kutai-timur/CF
in Show data source, the legend request to geonode fails due to layer = None:
https://www.geonode-gfdrrlab.org/geoserver/hazard/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=None

I will have a look to fully qualify these 3 cases regarding geonode data and thinkhazard processing.

**Comment by arnaud-morvan** [comment]
Concerning FL, the layer is private in geonode api: 
https://www.geonode-gfdrrlab.org/api/layers/1295/
https://www.geonode-gfdrrlab.org/account/login/?next=/layers/hazard:adm2_fu_v3_4bit
but the GetLegendGraphic return 200 with an image, so thinkhard believe it is public: 
https://www.geonode-gfdrrlab.org/geoserver/hazard/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=hazard:adm2_fu_v3_4bit

I might be possible to make a request on the api to know if layer is publicly available.

**Comment by arnaud-morvan** [comment]
Concerning CF, the layer is correctly returned by: https://www.geonode-gfdrrlab.org/api/layers/915/
but not returned by: https://www.geonode-gfdrrlab.org/api/layers/
So it is not updated and typename is empty in thinkhazard database.

**Comment by pvalsecc** [comment]
{"geonode_version": "2.8.1rc0", "meta": {"limit": 200, "next": "/api/layers/?limit=200&offset=200", "offset": 0,

**Comment by stufraser1** [comment]
@pvalsecc @arnaud-morvan 
It looks like I can download e.g. EQ-ET-GFDRR* now without logging into GeoNode. So looks to be fixed to me.
From your perspective is this resolved?
