### ISSUE TITLE
Hazard class should be "none" when there is no hazard

### ISSUE THREAD

**Issue by MamadioCMCC** [GFDRR/thinkhazard#854]
For some hazards, "nodata" is interpreted as "very low" hazard.

Some examples:
Coastal flood classified as "very low" where there is no coast (e.g. Switzerland, landlocked regions)
Similarly, cyclones are classified as "very low" on nodata areas (e.g. Italy)
Volcanic hazard classified as "low" where there are no volcanoes (e.g India)

**Comment by stufraser1** [comment]
This requires discussion.
- India is low, because of volcanoes located on Andaman Islands (its just not very visible on map due to small islands)
- Coastal flood does need updating to show land-locked ADM units as NoData
- I would agree, lets change CY to be NoData (so then it is also clear it is cyclone only, not other winds included)

This requires updating the raw hazard layers to a nodata value and reharvesting the data.

**Comment by MamadioCMCC** [comment]
Coastal flood and cyclones rasters are corrected: zeroes turned into nodata, should solve the issue with "low hazard".
